# Generated by Django 2.0 on 2018-02-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180130_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='catagory',
            field=models.CharField(choices=[('pxjg', '培训机构'), ('gr', '个人'), ('gx', '高校')], default='pxjg', max_length=20, verbose_name='机构类别'),
        ),
    ]
