# Generated by Django 2.0 on 2018-02-07 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_courseorg_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='catagory',
            new_name='category',
        ),
    ]
